"""
Synthetic Data Visualization Demo
=================================

This script visualizes the synthetic 3D and 4D particle data generated by
demo_synthetic_data.py using the ilabvis library.

Prerequisites:
    Run demo_synthetic_data.py first to generate the data files.

Usage:
    python demo_visualize_synthetic_data.py [--data {circle,sphere,gaussian,multi,moving,all}]

Options:
    --data  Specify which data to visualize (default: all)
            - circle: 2D circle slice
            - sphere: 3D sphere volume
            - gaussian: 3D Gaussian particle
            - multi: 3D volume with multiple particles
            - moving: 4D time series with moving particles
            - all: Visualize all data sequentially

Note:
    When visualizing "all" data, each visualization window must be closed
    before the next one appears. This is due to Qt's single QApplication
    constraint per process.
"""

import argparse
import sys
from pathlib import Path

import numpy as np
from PyQt6 import QtWidgets

# Add submodules to path for ilabvis
sys.path.insert(0, str(Path(__file__).parent.parent / "submodules" / "ilabvis"))

# Import ilabvis module first to register cleanup handlers
import ilabvis  # noqa: F401

from ilabvis.mouse_cursor2d import CursorVisualizer
from ilabvis.slice_visualizer import SlicingVisualizer

# Global QApplication instance to be shared across all visualizers
_qapp = None


def get_qapp():
    """Get or create a shared QApplication instance."""
    global _qapp
    if _qapp is None:
        # Check if a QApplication already exists
        _qapp = QtWidgets.QApplication.instance()
        if _qapp is None:
            _qapp = QtWidgets.QApplication([])
    return _qapp


def load_data(output_dir: Path) -> dict:
    """Load all synthetic data files."""
    data = {}

    files = {
        "circle": "circle_2d.npy",
        "sphere": "sphere_3d.npy",
        "gaussian": "gaussian_3d.npy",
        "multi": "multi_particles_3d.npy",
        "multi_positions": "multi_particles_3d_positions.npy",
        "moving": "moving_particles_4d.npy",
        "moving_positions": "moving_particles_4d_positions.npy",
    }

    for key, filename in files.items():
        filepath = output_dir / filename
        if filepath.exists():
            data[key] = np.load(filepath)
        else:
            print(f"Warning: {filename} not found. Run demo_synthetic_data.py first.")

    return data


def visualize_circle(data: dict) -> None:
    """Visualize 2D circle slice."""
    if "circle" not in data:
        print("Circle data not available.")
        return

    print("\n" + "=" * 60)
    print("Visualizing: 2D Circle Slice")
    print("=" * 60)
    print(f"Shape: {data['circle'].shape}")
    print("Controls:")
    print("  - Hover: Show position and pixel value")
    print("  - ROI: Drag to select region of interest")
    print("  - Histogram: Adjust contrast levels")
    print("Close the window to continue...")

    vis = CursorVisualizer(data["circle"])
    vis.run()


def visualize_sphere(data: dict) -> None:
    """Visualize 3D sphere volume."""
    if "sphere" not in data:
        print("Sphere data not available.")
        return

    print("\n" + "=" * 60)
    print("Visualizing: 3D Sphere Volume")
    print("=" * 60)
    print(f"Shape: {data['sphere'].shape} (Z, Y, X)")
    print("Controls:")
    print("  - Left panel: XY slice (lateral view)")
    print("  - Right panel: XZ slice (axial view)")
    print("  - Yellow line: Drag to change slice position")
    print("  - Auto Contrast: Adjust levels automatically")
    print("Close the window to continue...")

    vis = SlicingVisualizer(data["sphere"], indexing="zyx")
    vis.run()


def visualize_gaussian(data: dict) -> None:
    """Visualize 3D Gaussian particle."""
    if "gaussian" not in data:
        print("Gaussian data not available.")
        return

    print("\n" + "=" * 60)
    print("Visualizing: 3D Gaussian Particle (Anisotropic)")
    print("=" * 60)
    print(f"Shape: {data['gaussian'].shape} (Z, Y, X)")
    print("Note: This particle has anisotropic sigma (z=3, y=5, x=5)")
    print("      Observe the different spread in XY vs XZ views.")
    print("Controls:")
    print("  - Left panel: XY slice (lateral view)")
    print("  - Right panel: XZ slice (axial view)")
    print("  - Yellow line: Drag to change slice position")
    print("Close the window to continue...")

    vis = SlicingVisualizer(data["gaussian"], indexing="zyx")
    vis.run()


def visualize_multi_particles(data: dict) -> None:
    """Visualize 3D volume with multiple particles."""
    if "multi" not in data:
        print("Multi-particle data not available.")
        return

    print("\n" + "=" * 60)
    print("Visualizing: 3D Volume with Multiple Particles")
    print("=" * 60)
    print(f"Shape: {data['multi'].shape} (Z, Y, X)")
    if "multi_positions" in data:
        positions = data["multi_positions"]
        print(f"Number of particles: {len(positions)}")
        print("Ground truth positions (Z, Y, X):")
        for i, pos in enumerate(positions):
            print(f"  Particle {i + 1}: {pos}")
    print("Controls:")
    print("  - Left panel: XY slice (lateral view)")
    print("  - Right panel: XZ slice (axial view)")
    print("  - Yellow line: Drag to change slice position")
    print("  - Navigate through Z to find particles")
    print("Close the window to continue...")

    vis = SlicingVisualizer(data["multi"], indexing="zyx")
    vis.run()


def visualize_moving_particles(data: dict) -> None:
    """Visualize 4D time series with moving particles."""
    if "moving" not in data:
        print("Moving particles data not available.")
        return

    print("\n" + "=" * 60)
    print("Visualizing: 4D Time Series with Moving Particles")
    print("=" * 60)
    print(f"Shape: {data['moving'].shape} (T, Z, Y, X)")
    if "moving_positions" in data:
        positions = data["moving_positions"]
        print(f"Number of particles: {positions.shape[0]}")
        print(f"Number of frames: {positions.shape[1]}")
    print("\nNote: Time dimension is treated as Z-axis in the visualizer.")
    print("      Use the slice control to navigate through time frames.")
    print("Controls:")
    print("  - Left panel: Shows a single time frame (max projection or slice)")
    print("  - Right panel: Shows temporal evolution")
    print("  - Yellow line: Drag to change time frame")
    print("  - Use 'Save Video' to export animation")
    print("Close the window to continue...")

    # For 4D data, we have two options:
    # 1. Visualize as 3D by taking max projection along Z for each time frame
    # 2. Visualize each time frame as a 3D volume

    # Option 1: Create max projection for time visualization
    max_proj = data["moving"].max(axis=1)  # Max along Z: (T, Y, X)
    print(f"\nShowing max projection along Z: {max_proj.shape} (T, Y, X)")

    vis = SlicingVisualizer(max_proj, indexing="zyx")
    vis.run()

    # Option 2: Also offer to view a single time frame in 3D
    print("\nWould you like to view a specific time frame in 3D?")
    print("Showing first frame (t=0) as 3D volume...")

    first_frame = data["moving"][0]  # First time frame: (Z, Y, X)
    vis2 = SlicingVisualizer(first_frame, indexing="zyx")
    vis2.run()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Visualize synthetic particle data using ilabvis"
    )
    parser.add_argument(
        "--data",
        type=str,
        default="all",
        choices=["circle", "sphere", "gaussian", "multi", "moving", "all"],
        help="Which data to visualize (default: all)",
    )
    args = parser.parse_args()

    # Initialize QApplication once at the start to avoid mutex errors
    # when creating multiple visualizers sequentially
    get_qapp()

    output_dir = Path("./output/synthetic")
    if not output_dir.exists():
        print(f"Error: Output directory not found: {output_dir}")
        print("Please run demo_synthetic_data.py first to generate the data.")
        sys.exit(1)

    print("Loading synthetic data...")
    data = load_data(output_dir)

    if not data:
        print("Error: No data files found.")
        print("Please run demo_synthetic_data.py first to generate the data.")
        sys.exit(1)

    print(f"Loaded {len(data)} data files.")

    visualizers = {
        "circle": visualize_circle,
        "sphere": visualize_sphere,
        "gaussian": visualize_gaussian,
        "multi": visualize_multi_particles,
        "moving": visualize_moving_particles,
    }

    if args.data == "all":
        for visualize_func in visualizers.values():
            visualize_func(data)
    else:
        visualizers[args.data](data)

    print("\n" + "=" * 60)
    print("Visualization complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()
